### ISSUE TITLE
Battery and history

### ISSUE THREAD

**Issue by citizenxnz** [EDelsman/com.coulisse.motionblinds#3]
Thanks the great app!

I noticed that for curtains it doesn't show the battery level - even though the curtain motor is a bi directional motor reporting battery to the hub and the app

And on both curtains and roller blinds there is no history. It would be so fantastic if that could please be included

Thanks!

**Comment by EDelsman** [comment]
It is strange that you say battery level isn't there because it should be. The TBDU even have an option to show both battery levels. If the value isn't there then the gateway isn't sending them. Are you using MotionBlinds or Brel hub/blinds? The functionality is designed for Motion, Brel may not be fully compatible.

Could you enable full logging in the settings, restart the app and send me a diagnostics report?

As for history, Homey automatically adds on/off history to devices but curtains don't have on/off capability. I do not know if it is possible to add history to other capabilities, I have to look in to that but I have not seen any other device do it either.

**Comment by citizenxnz** [comment]
Thanks so much for the quick reply!

I'm using a Dooya/Connector hub dd7002b. I am based in New Zealand, purchased here https://www.ismartwindow.co.nz/DD7002B_WIFI_bridge.html

It was programmed to connect via the Connector app, but since the Brel app came out on Homey I relinked it to the Brel Home app and the curtains & blinds are now setup in there.

I've just done the diagnostic report as requested
5bc9b18f-7259-4130-a2c7-61544054e0cb

And thanks for update on history - hope there are some options available.

**Comment by EDelsman** [comment]
I see what is going on: some of your curtains report a voltage mode AC instead of DC, so Homey thinks these are mains powered and not run on battery. The documentation says battery level is DC motor only. I do see battery levels though, corresponding to a 4cell battery. Are the curtains battery powered or mains powered?

**Comment by citizenxnz** [comment]
Ah, that is interesting - thank you
They are battery powered. 
I just checked the Brel app - yes I can see it shows the power plug sign - which is very strange as I did see it as battery and the level when is was in the Connector app
I am not sure how to get the hub to recognise them as battery powered

**Comment by EDelsman** [comment]
Well, what I could try is to ignore the voltageMode if the batteryLevel makes sense. However, if I get complaints from people with mains powered devices I may have to rethink that. 
I pushed a version to the Homey test channel to do just that, could you see if that fixes it?
https://homey.app/nl-nl/app/com.coulisse.motionblinds/Motion-Blinds/test/

**Comment by citizenxnz** [comment]
That is perfect, it shows the battery now. Thank you!

**Comment by EDelsman** [comment]
Good to hear. Don't forget to turn full logging off. I'll ask Athom to push this version to production.
